version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cutai
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=cutai
      - PGHOST=db
      - PGPORT=5432
      # Add OpenRouter API key environment variable (to be set by user)
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always
    command: > 
      bash -c "
        echo 'Waiting for database to be ready...' &&
        sleep 5 &&
        python -c 'from database import init_db; init_db()' &&
        streamlit run app.py --server.port=5000 --server.address=0.0.0.0
      "

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cutai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: